// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import axios from 'axios';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./style.css']
})
export class AppComponent implements OnInit {
  data: any = {};
  location: string = 'Saint Petersburg';

  ngOnInit() {
    this.fetchData();
    this.location = '';
  }

  fetchData() {
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${this.location}&units=metric&appid=b7b5b933dd0f0d4401f993ab971a3a8b`;
    axios.get(url).then((response) => {
      this.data = response.data;
    });
  }

  searchLocation() {
    this.fetchData();
    this.location = '';
  }
}
<div class="app">
  <div class="search">
    <input
      [(ngModel)]="location"
      (keyup.enter)="searchLocation()"
      placeholder="Enter location"
      type="text"
    />
  </div>
  <div class="container">
    <div class="top">
      <div class="location">
        <p>{{ data?.name }}</p>
      </div>
      <div class="temp">
        <h1 *ngIf="data?.main">{{ data.main.temp }}°C</h1>
      </div>
      <div class="description">
        <p *ngIf="data?.weather">{{ data.weather[0].main }}</p>
      </div>
    </div>
    <div class="bottom" *ngIf="data?.name">
      <div class="feels">
        <p *ngIf="data?.main" class="bold">{{ data.main.feels_like }}°C</p>
        <p>Feels like</p>
      </div>
      <div class="humidity">
        <p *ngIf="data?.main" class="bold">{{ data.main.humidity }}%</p>
        <p>Humidity</p>
      </div>
      <div class="wind">
        <p *ngIf="data?.wind" class="bold">{{ data.wind.speed }} KPH</p>
        <p>Wind Speed</p>
      </div>
    </div>
  </div>
</div>

// svelte/src/App.svelte
<script>
  import { onMount, useState } from "svelte";
  import axios from "axios";

  let data = {};
  let location = "Saint Petersburg";

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=metric&appid=b7b5b933dd0f0d4401f993ab971a3a8b`;

  const searchLocation = (event) => {
    if (event.key === "Enter") {
      axios.get(url).then((response) => {
        data = response.data;
      });
      location = "";
    }
  };

  onMount(() => {
    axios.get(url).then((response) => {
      data = response.data;
    });
    location = "";
  });
</script>

	<div class="app">
	<div class="search">
		<input
		value={location}
		on:input={(event) => (location = event.target.value)}
		on:keypress={searchLocation}
		placeholder="Enter location"
		type="text"
		/>
	</div>
	<div class="container">
		<div class="top">
		<div class="location">
			<p>{data.name}</p>
		</div>
		<div class="temp">
			<h1>{data.main.temp}°C</h1>
		</div>
		<div class="description">
			<p>{data.weather[0].main}</p>
		</div>
		</div>
		<div class="bottom">
			<div class="feels">
				<p class="bold">{data.main.feels_like}°C</p>
			<p>Feels like</p>
			</div>
			<div class="humidity">
			<p class="bold">{data.main.humidity}%</p>
			<p>Humidity</p>
			</div>
			<div class="wind">
			<p class="bold">{data.wind.speed} KPH</p>
			<p>Wind Speed</p>
			</div>
		</div>
	</div>
	</div>
